-- 0009: Weather Data, Disaster Events, Road Incidents
-- Three tables covering environmental conditions and field-reported road events.

-- ---------------------------------------------------------------------------
-- Weather data ingested periodically by sync-weather Edge Function / Cron
-- ---------------------------------------------------------------------------
create table public.weather_data (
  id                uuid        primary key default extensions.uuid_generate_v4(),
  location_id       uuid        references public.locations (id),
  recorded_at       timestamptz not null,
  temperature_c     double precision,
  humidity_percent  double precision,
  rainfall_mm       double precision,
  wind_speed_kmph   double precision,
  visibility_km     double precision,
  pressure_hpa      double precision,
  weather_condition text,
  source            text,
  raw_data          jsonb,
  created_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Disaster events from external providers and field reports
-- ---------------------------------------------------------------------------
create table public.disaster_events (
  id              uuid                       primary key default extensions.uuid_generate_v4(),
  type            public.disaster_type_enum  not null,
  severity        integer                    check (severity between 1 and 5),
  title           text,
  description     text,
  location_id     uuid                       references public.locations (id),
  geometry        extensions.geography,
  route_id        uuid                       references public.routes (id),
  started_at      timestamptz,
  ended_at        timestamptz,
  probability     double precision           check (probability between 0 and 1),
  source          text,
  source_event_id text        unique,
  verified        boolean                    not null default false,
  district        text,
  state           text,
  created_at      timestamptz                not null default now(),
  updated_at      timestamptz                not null default now()
);

-- ---------------------------------------------------------------------------
-- Road incidents reported by field officers (ReportScreen 6-step wizard)
-- ---------------------------------------------------------------------------
create table public.road_incidents (
  id           uuid                        primary key default extensions.uuid_generate_v4(),
  -- Display ID in INC-YYYY-NNN format; populated by trigger
  incident_ref text                        unique,
  reported_by  uuid                        references auth.users (id),
  location_id  uuid                        references public.locations (id),
  geometry     extensions.geography(Point,4326),
  route_id     uuid                        references public.routes (id),
  category     public.incident_type_enum   not null,
  title        text,
  description  text,
  severity     public.priority_enum        not null default 'medium',
  media_path   text,
  assigned_to  uuid                        references auth.users (id),
  status       public.incident_status_enum not null default 'pending',
  verified     boolean                     not null default false,
  verified_by  uuid                        references auth.users (id),
  verified_at  timestamptz,
  district     text,
  state        text,
  sync_source  text                        not null default 'online',  -- 'online' | 'offline'
  sync_status  public.sync_status_enum     not null default 'synced',
  created_at   timestamptz                 not null default now(),
  updated_at   timestamptz                 not null default now()
);

comment on table public.road_incidents is
  'Field officer incident reports submitted via the 6-step ReportScreen wizard.';
comment on column public.road_incidents.incident_ref is
  'Human-readable reference like INC-2026-041. Generated by trigger on insert.';
comment on column public.road_incidents.sync_status is
  'Tracks offline-first sync state. pending = queued locally; synced = confirmed in DB; failed = retry needed.';
